### ISSUE TITLE
Tutorials are 403 Forbidden

### ISSUE THREAD

**Issue by Daivuk** [jbikker/bvh_article#1]
Hi, I loved your tutorials on BVH. I was saving them for reference. And it appears that the site is not inaccessible anymore: https://jacco.ompf2.com/2022/04/13/how-to-build-a-bvh-part-1-basics/
Getting **403 Forbidden**.

Could be a temporary glitch

**Comment by OptimisticMonkey** [comment]
Same issue for me

**Comment by jin-qifeng** [comment]
you can access by web archive
https://web.archive.org/web/20220413163159/https://jacco.ompf2.com/2022/04/13/how-to-build-a-bvh-part-1-basics/

**Comment by jbikker** [comment]
This should now be resolved. Subscription has been extended to 'pro', wp caching installed.
