### ISSUE TITLE
missing macros in win_tiny.h

### ISSUE THREAD

**Issue by thomasjungblut** [jbikker/bvh_article#2]
Thanks for your great blog posts, I was just trying to play around with the code a bit this evening.

Immediately had troubles to get this to compile in a fresh installation of VS2022. Namely the `DEFINE_ENUM_FLAG_OPERATORS` from winnt.h seems missing in the win_tiny.h nowadays. Including the bigger `windows.h` again and commenting the tiny header works again:

```cpp
#include "windows.h"
// #include "lib/win_tiny.h" // windows.h replacement for faster builds
```

https://github.com/jbikker/bvh_article/blob/c127c63ae84df58ec6931fc6a829921c711f9826/template/precomp.h#L79

I'm on win11 with a fairly recent sdk version: 10.0.22621.0 that I just downloaded. Thought I'll leave a quick note here before others spend hours on figuring out what was missing.

Cheers,
Thomas

**Comment by jbikker** [comment]
Thanks for your comment. The win_tiny.h was a bit of an experiment, and it doesn't really appear to help. On the next push this will be undone. The large set of defines before windows.h will stay though; these should not hurt and may help - fingers crossed. :)
