### ISSUE TITLE
ray direction calculation

### ISSUE THREAD

**Issue by XiaotianM** [jbikker/bvh_article#5]
Hi, I am a little confused about the way to calculate orientation calculation.
in chapter2:
https://github.com/jbikker/bvh_article/blob/89bf112b7ca8c277ac0a311119aa2e29d5ee41f1/faster.cpp#L277C1-L279C57
```c++
ray.O = float3( -1.5f, -0.2f, -2.5f );
float3 pixelPos = ray.O + p0 + (p1 - p0) * ((x + u) / (float)SCRWIDTH) + (p2 - p0) * ((y + v) / (float)SCRHEIGHT);
ray.D = normalize( pixelPos - ray.O ), ray.t = 1e30f;
``` 
Why need to add ray.O for pixelPos, and minus the ray.O to calculate ray,D.  It seems the rays are emitted from (0,0,0), but the ray origin point is still ( -1.5f, -0.2f, -2.5f )

and in chapter1:
In chapter1:
https://github.com/jbikker/bvh_article/blob/89bf112b7ca8c277ac0a311119aa2e29d5ee41f1/basics.cpp#L182C1-L184C41
```c++
float3 pixelPos = p0 + (p1 - p0) * (x / (float)SCRWIDTH) + (p2 - p0) * (y / (float)SCRHEIGHT);
ray.D = normalize( pixelPos - ray.O );
``` 
there is different calculation for pixelPos (no ray.O added)

**Comment by jbikker** [comment]
Hi,

It's indeed a bit weird that in chapter 2 ray.O is added to the pixel
position. It is best to calculate all coordinates in 'world space';
assuming the screen corners p0, p1 and p2 are in world space, the pixel
position should be calculated as P(u,v) = p0 + u(p1 - p0) + v(p2 - p0).
I am not sure why I did this different in chaper 2, it looks like the pixel
position is now relative to the ray origin but then the ray.D calculation
doesn't make sense...

Sorry for the confusion!

- Jacco.

**Comment by jbikker** [comment]
Article and code has been updated; should be better now. Let me know if you
find anything else.

- Jacco.

**Comment by XiaotianM** [comment]
HI Jacco,

Thank you very much for your replay.
In fact, in other chapter's code, there also adds ray.O for pixel position calculation.
Anyway, I got your points now. This issue can be closed.
